name: ci

on: [push, pull_request]

jobs:
  test:
    name: tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: true

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Download Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Lint sources
        if: matrix.os == 'ubuntu-latest'
        run: make lint

      - name: Check format
        if: matrix.os == 'ubuntu-latest'
        run: make fmt

      - name: Run tests
        run: make test
