name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-deno:
    name: Unit tests · Deno
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno task lint
      - run: deno fmt --check
      - run: deno task test

  test-node:
    name: Unit tests · Node
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run typecheck
      - run: npm test

  integration-deno:
    name: Integration · Deno · ${{ matrix.ircd }}
    runs-on: ubuntu-latest
    needs: [test-deno, test-node]

    strategy:
      matrix:
        ircd: [ergo, inspircd]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno task test:integration:${{ matrix.ircd }}

  integration-node:
    name: Integration · Node · ergo
    runs-on: ubuntu-latest
    needs: [test-deno, test-node]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run test:integration:ergo
