name: Publish to JSR

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Publish to JSR
        run: deno publish
