name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  tag:
    name: Tag
    uses: ./.github/workflows/release-tag.yml
    with:
      release-type: ${{ inputs.release-type }}

  gh:
    name: GitHub
    needs: [tag]
    uses: ./.github/workflows/release-gh.yml
    with:
      ref: main

  jsr:
    name: JSR
    needs: [tag]
    uses: ./.github/workflows/release-jsr.yml
    with:
      ref: main

  npm:
    name: npm
    needs: [tag]
    uses: ./.github/workflows/release-npm.yml
    with:
      ref: main
