name: test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    uses: ./.github/workflows/check.yml

  unit:
    name: Unit tests
    needs: [check]
    uses: ./.github/workflows/test-unit.yml

  coverage:
    name: Coverage
    needs: [unit]
    uses: ./.github/workflows/test-coverage.yml

  integration:
    name: Integration
    needs: [unit]
    uses: ./.github/workflows/test-integration.yml
